name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
      working-directory: ./src/
      
    - name: Execute CI
      run: npm ci
      working-directory: ./src/
      
    - name: Build
      run: npm run build --if-present
      working-directory: ./src/
      
    - name: Run tests
      run: npm test
      working-directory: ./src/
